title: Kalo Stems
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-minima
github:
  is_project_page: true
  repository_url: https://github.com/kalo-stems/kalo-stems.github.io
gems:
  - jekyll-mentions
